In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/employee_data_messy (1).csv")

In [ ]:
print("-------Data Summary----")
df.info()

-------Data Summary----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   35 non-null     int64
 1   Name         35 non-null     object
 2   Age          33 non-null     object
 3   Salary       34 non-null     object
 4   Department   34 non-null     object
 5   JoiningDate  34 non-null     object
 6   Email        34 non-null     object
 7   City         34 non-null     object
dtypes: int64(1), object(7)
memory usage: 2.3+ KB

In [ ]:
print("\n---Missing value Tally----")
print(df.isnull().sum())

---Missing value Tally----
EmployeeID     0
Name           0
Age            2
Salary         1
Department     1
JoiningDate    1
Email          1
City           1
dtype: int64

In [ ]:
# drop draws were critical identifying crteria is absent
df_clean=df.dropna(subset=("Name"))
print(df_clean.head(5))

   EmployeeID          Name     Age Salary Department JoiningDate  \
0         101     John Doe       25  50000         IT  2022-01-15
1         102    Jane Smith      28  55000         HR  2021-11-10
2         103  Mike Johnson     NaN  62000    Finance  2020-05-20
3         104  Sarah Wilson  Thirty  58000         IT  2022-03-12
4         105   David Brown      35    NaN  Marketing  2019-07-01

                    Email       City
0      john.doe@gmail.com  Kathmandu
1    jane.smith@gmail.com    Pokhara
2  mike.johnson@gmail.com   Lalitpur
3  sarah.wilson@gmail.com  Bhaktapur
4   david.brown@gmail.com     Butwal

In [ ]:
#immutating AND COVERting non numeric va;lues
df_clean['salary']=df_clean['Salary'].astype(str).replace
df_clean['Salary']=pd.to_numeric(df_clean['Salary'],errors='coerce')


salary_median=df_clean['Salary'].median()
df_clean['Salary'].fillna(salary_median,inplace=True)


#replace missing categorical fields(department) with a text
df_clean["Department"]=df_clean["Department"].fillna("Unassigned")
print(df_clean.head(5))

   EmployeeID          Name     Age   Salary Department JoiningDate  \
0         101     John Doe       25  50000.0         IT  2022-01-15
1         102    Jane Smith      28  55000.0         HR  2021-11-10
2         103  Mike Johnson     NaN  62000.0    Finance  2020-05-20
3         104  Sarah Wilson  Thirty  58000.0         IT  2022-03-12
4         105   David Brown      35  55000.0  Marketing  2019-07-01

                    Email       City  \
0      john.doe@gmail.com  Kathmandu
1    jane.smith@gmail.com    Pokhara
2  mike.johnson@gmail.com   Lalitpur
3  sarah.wilson@gmail.com  Bhaktapur
4   david.brown@gmail.com     Butwal

                                              salary
0  <bound method NDFrame.replace of 0      50000\...
1  <bound method NDFrame.replace of 0      50000\...
2  <bound method NDFrame.replace of 0      50000\...
3  <bound method NDFrame.replace of 0      50000\...
4  <bound method NDFrame.replace of 0      50000\...

/tmp/ipykernel_1226/782000358.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['Salary'].fillna(salary_median,inplace=True)

In [ ]:
print("------Missing Values-----")
# Check for missing values in specific columns
print(df_clean[["Name", "salary", "Department"]].isnull().sum())

------Missing Values-----
Name          0
salary        0
Department    0
dtype: int64

In [ ]:
duplicate_count=df_clean.duplicated().sum()
print(f"Total valid unique records remaining: {len(df_clean)}")

Total valid unique records remaining: 35

In [ ]:
df_clean['Age']=df_clean['Age'].replace("Thirty","30")
df_clean['Age']=df_clean['Age'].replace("twenty-eight","28")

In [ ]:
df_clean['Age'] =pd.to_numeric(df_clean['Age'],errors='coerce')

In [ ]:
age_median=df_clean['Age'].median()
df_clean['Age']=df_clean['Age'].fillna(age_median).astype(int)

In [ ]:
#standarize and transform dta strings intp true datetime format structure
df_clean["JoiningDate"]=pd.to_datetime(df_clean["JoiningDate"],errors='coerce')

In [ ]:
print("------Structural data type conversion verified----")
print(df_clean[['Age', 'JoiningDate']].dtypes)

------Structural data type conversion verified----
Age                     int64
JoiningDate    datetime64[ns]
dtype: object

In [ ]:
df_clean['Name']=df_clean['Name'].str.strip()
df_clean['City']=df_clean['City'].str.strip()

In [ ]:
df_clean['Name']=df_clean['Name'].str.title()
df_clean['City']=df_clean['City'].str.title()

In [ ]:
df_clean["Department"]=df_clean["Department"].str.upper()

In [ ]:
df_clean['City']=df_clean['City'].fillna('Unknown')

In [ ]:
print("-------Cleaned text field------")
print(df_clean[['Name', 'City', 'Department']].head(10))

-------Cleaned text field------
             Name       City  Department
0        John Doe  Kathmandu          IT
1      Jane Smith    Pokhara          HR
2    Mike Johnson   Lalitpur     FINANCE
3    Sarah Wilson  Bhaktapur          IT
4     David Brown     Butwal   MARKETING
5     Emily Davis    Chitwan          HR
6    Chris Taylor     Dharan     FINANCE
7  Jessica Miller  Kathmandu          IT
8    Robert White    Pokhara  MANAGEMENT
9      Lisa Green   Janakpur          HR

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   35 non-null     int64
 1   Name         35 non-null     object
 2   Age          35 non-null     int64
 3   Salary       35 non-null     float64
 4   Department   35 non-null     object
 5   JoiningDate  33 non-null     datetime64[ns]
 6   Email        34 non-null     object
 7   City         35 non-null     object
 8   salary       35 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 2.6+ KB

In [ ]:
df_clean['Email'] = df_clean['Email'].fillna('unknown@email.com')

In [ ]:
df_clean = df_clean.dropna(subset=['Email'])

In [ ]:
missing_email_row = df_clean[df_clean['Email'].isna()]
print(missing_email_row)

Empty DataFrame
Columns: [EmployeeID, Name, Age, Salary, Department, JoiningDate, Email, City, salary]
Index: []

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   35 non-null     int64
 1   Name         35 non-null     object
 2   Age          35 non-null     int64
 3   Salary       35 non-null     float64
 4   Department   35 non-null     object
 5   JoiningDate  33 non-null     datetime64[ns]
 6   Email        35 non-null     object
 7   City         35 non-null     object
 8   salary       35 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 2.6+ KB

In [ ]:
# cleaniing the department data
to_drop=['Department']

In [ ]:
df.head()

,EmployeeID,Name,Age,Salary,Department,JoiningDate,Email,City
0,101,John Doe,25,50000,IT,2022-01-15,john.doe@gmail.com,Kathmandu
1,102,Jane Smith,28,55000,HR,2021-11-10,jane.smith@gmail.com,Pokhara
2,103,Mike Johnson,NaN,62000,Finance,2020-05-20,mike.johnson@gmail.com,Lalitpur
3,104,Sarah Wilson,Thirty,58000,IT,2022-03-12,sarah.wilson@gmail.com,Bhaktapur
4,105,David Brown,35,NaN,Marketing,2019-07-01,david.brown@gmail.com,Butwal

In [ ]:
df_clean['Department'].head(10)

0            IT
1            HR
2       FINANCE
3            IT
4     MARKETING
5            HR
6       FINANCE
7            IT
8    MANAGEMENT
9            HR
Name: Department, dtype: object

In [ ]:
df.loc()

In [ ]:
pub = df_clean['Department']
IT = pub.str.contains('IT')
IT[:5]

0     True
1    False
2    False
3     True
4    False
Name: Department, dtype: bool

In [ ]:
df_clean['Department'].head()

0           IT
1           HR
2      FINANCE
3           IT
4    MARKETING
Name: Department, dtype: object

In [ ]:
row_df=pd.read_csv("/content/employee_data_messy (1).csv", header=2)

In [ ]:
row_df.head()

,102,Jane Smith,28,55000,HR,2021-11-10,jane.smith@gmail.com,Pokhara
0,103,Mike Johnson,NaN,62000,Finance,2020-05-20,mike.johnson@gmail.com,Lalitpur
1,104,Sarah Wilson,Thirty,58000,IT,2022-03-12,sarah.wilson@gmail.com,Bhaktapur
2,105,David Brown,35,NaN,Marketing,2019-07-01,david.brown@gmail.com,Butwal
3,106,Emily Davis,29,53000,HR,2021/08/15,emily.davis@gmail.com,Chitwan
4,107,Chris Taylor,31,61000,Finance,NaN,chris.taylor@gmail.com,Dharan

In [ ]:
# Remove duplicate rows
df = df.drop_duplicates()

In [ ]:
# Reset index after cleaning
df = df.reset_index(drop=True)

In [ ]:
# Convert email addresses to lowercase
df['Email'] = df['Email'].str.lower()

In [ ]:
# Remove extra spaces from names
df['Name'] = df['Name'].str.strip()

In [ ]:
# Standardize city names
df['City'] = df['City'].str.title()

In [ ]:
# Check for duplicate emails
print(df['Email'].duplicated().sum())

2

In [ ]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   35 non-null     int64
 1   Name         35 non-null     object
 2   Age          35 non-null     int64
 3   Salary       35 non-null     float64
 4   Department   35 non-null     object
 5   JoiningDate  33 non-null     datetime64[ns]
 6   Email        35 non-null     object
 7   City         35 non-null     object
 8   salary       35 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 2.6+ KB

In [ ]:
# Sort records by joining date
df = df.sort_values(by='JoiningDate')

In [ ]:
# Sort records by joining date and reset index
df = df.sort_values(by='JoiningDate').reset_index(drop=True)

In [ ]:
df = df.reset_index(drop=True)